### ISSUE TITLE
MaaX ARM64 版本中的 node-ffi-napi 打包错误

### ISSUE THREAD

**Issue by cubesky** [MaaAssistantArknights/MeoAsstElectronUI#197]
### 问题描述

MaaX ARM64 版本中的 node-ffi-napi 打包了 X86-64 版本的 ffi-bindings.node 造成无法启动。

### 日志文件

```[10841:0822/092613.505894:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
[10840:0822/092613.505934:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
[10838:0822/092613.511966:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /root/maa-x-linux-arm64/resources/app/node_modules/@tigerconnect/ffi-napi/build/Release/ffi_bindings.node: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at load (/root/maa-x-linux-arm64/resources/app/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/root/maa-x-linux-arm64/resources/app/node_modules/@tigerconnect/ffi-napi/lib/bindings.js:8:43)
[10838:0822/092614.214164:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[10838:0822/092614.214604:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[10838:0822/092614.219221:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[10838:0822/092614.219259:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[10838:0822/092614.219698:ERROR:address_tracker_linux.cc(225)] Could not bind NETLINK socket: Permission denied (13)
[10838:0822/092614.219764:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
[10838:0822/092614.274122:ERROR:udev_watcher.cc(52)] Failed to initialize a udev monitor.
[10838:0822/092617.773212:ERROR:zygote_communication_linux.cc(291)] Failed to send GetTerminationStatus message to zygote
```

### 截图

![image](https://github.com/MaaAssistantArknights/MaaX/assets/8038511/ed87ad96-a3b7-40f7-8c13-41c401c09867)

### 还有别的吗？

运行于 RedMi Note 12 Turbo 的 Termux 中的 PRoot OpenSUSE 包含 VNC X11。
![image](https://github.com/MaaAssistantArknights/MaaX/assets/8038511/79077547-90c9-4027-b28b-e78be783692b)

**Comment by bakashigure** [comment]
Action 里交叉编译的时候有宏传漏了, 导致这个文件编译架构错误, 从 `arm64` 变成 `x86_64` , 正好项目有更换`ffi`的打算, 此问题会持续跟进.
