### ISSUE TITLE
[linux] 启动时卡死

### ISSUE THREAD

**Issue by Eletary** [MaaAssistantArknights/MeoAsstElectronUI#216]
### 问题描述

使用 README 中的方式编译后运行 maa-x，然后界面会卡死

### 日志文件

我没找到日志文件位置，以下为命令行日志:

```
2024-05-05 20:30:10.468 INFO    [main /resources/app/packages/main/index.ts:28:8 Object.<anonymous>] Electron version: 26.0.0
2024-05-05 20:30:10.699 INFO    [main /resources/app/packages/main/index.ts:29:8 Object.<anonymous>] Chromium version: 116.0.5845.82
2024-05-05 20:30:10.700 INFO    [main /resources/app/packages/main/index.ts:30:8 Object.<anonymous>] Node version: 18.16.1
(node:45176) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/ppip/MaaX/out/maa-x-linux-x64/resources/app/node_modules/ps-list/index.js from /home/ppip/MaaX/out/maa-x-linux-x64/resources/app/dist/main/linuxAdapter-0628f468.js not supported.
Instead change the require of index.js in /home/ppip/MaaX/out/maa-x-linux-x64/resources/app/dist/main/linuxAdapter-0628f468.js to a dynamic import() which is available in all CommonJS modules.
    at Function._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.<anonymous> (/home/ppip/MaaX/out/maa-x-linux-x64/resources/app/dist/main/linuxAdapter-0628f468.js:1:122)
    at Function._load (node:electron/js2c/asar_bundle:2:13330)
    at /home/ppip/MaaX/out/maa-x-linux-x64/resources/app/dist/main/index-ff483208.js:30:14417
    at async L1 (/home/ppip/MaaX/out/maa-x-linux-x64/resources/app/dist/main/index-ff483208.js:30:14384)
    at async /home/ppip/MaaX/out/maa-x-linux-x64/resources/app/dist/main/index-ff483208.js:30:14479
(Use `maa-x --trace-warnings ...` to show where the warning was created)
(node:45176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2024-05-05 20:30:10.883 SILLY   [main /resources/app/packages/main/storageManager/index.ts:68:12 ys.<anonymous>] configuration saved
2024-05-05 20:30:11.097 INFO    [main /resources/app/packages/main/index.ts:62:14 _c] module WindowManager-v1.0.0 loaded.
2024-05-05 20:30:11.098 INFO    [main /resources/app/packages/main/index.ts:62:14 _c] module StorageManager-v1.0.0 loaded.
2024-05-05 20:30:11.099 INFO    [main /resources/app/packages/main/index.ts:62:14 _c] module CoreLoader-v1.0.0 loaded.
2024-05-05 20:30:11.100 INFO    [main /resources/app/packages/main/index.ts:62:14 _c] module DeviceDetector-v1.0.0 loaded.
2024-05-05 20:30:11.101 INFO    [main /resources/app/packages/main/index.ts:62:14 _c] module DownloadManager-v1.0.0 loaded.
2024-05-05 20:30:11.101 INFO    [main /resources/app/packages/main/index.ts:62:14 _c] module ComponentManager-v1.0.0 loaded.
[45247:0505/203011.419596:ERROR:platform_thread_posix.cc(155)] pthread_create: Resource temporarily unavailable (11)
[45247:0505/203012.413048:ERROR:platform_thread_posix.cc(155)] pthread_create: Resource temporarily unavailable (11)
[45247:0505/203012.413072:ERROR:platform_thread_posix.cc(155)] pthread_create: Resource temporarily unavailable (11)
[45247:0505/203012.497619:ERROR:platform_thread_posix.cc(155)] pthread_create: Resource temporarily unavailable (11)
[45247:0505/203012.497615:ERROR:platform_thread_posix.cc(155)] pthread_create: Resource temporarily unavailable (11)
[45247:0505/203012.538826:ERROR:platform_thread_posix.cc(155)] pthread_create: Resource temporarily unavailable (11)
2024-05-05 20:30:13.017 SILLY   [main /resources/app/packages/main/utils/ipc-main.ts:26:12 <anonymous>] Receive ipcMain event: main.WindowManager:isMaximized
2024-05-05 20:30:13.021 SILLY   [main /resources/app/packages/main/utils/ipc-main.ts:26:12 <anonymous>] Receive ipcMain event: main.CoreLoader:upgrade
2024-05-05 20:30:13.022 INFO    [main /resources/app/packages/main/coreLoader/index.ts:327:12 cn.Upgrade] Start upgrade core
2024-05-05 20:30:13.025 SILLY   [main /resources/app/packages/main/utils/ipc-main.ts:26:12 <anonymous>] Receive ipcMain event: main.StorageManager:get
2024-05-05 20:30:13.026 SILLY   [main /resources/app/packages/main/utils/ipc-main.ts:26:12 <anonymous>] Receive ipcMain event: main.StorageManager:get
2024-05-05 20:30:13.027 SILLY   [main /resources/app/packages/main/utils/ipc-main.ts:26:12 <anonymous>] Receive ipcMain event: main.StorageManager:get
2024-05-05 20:30:13.028 SILLY   [main /resources/app/packages/main/utils/ipc-main.ts:26:12 <anonymous>] Receive ipcMain event: main.StorageManager:get
2024-05-05 20:30:13.029 SILLY   [main /resources/app/packages/main/utils/ipc-main.ts:26:12 <anonymous>] Receive ipcMain event: main.StorageManager:get
2024-05-05 20:30:13.030 SILLY   [main /resources/app/packages/main/utils/ipc-main.ts:26:12 <anonymous>] Receive ipcMain event: main.StorageManager:get
```

### 截图

卡死界面

![image](https://github.com/MaaAssistantArknights/MaaX/assets/86780576/5dc2aca8-ab4e-4ca7-b3a5-1058f2d6e009)

### 还有别的吗？

```
                   -`                    ppip@arch 
                  .o+`                   --------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Zenbook UX3402ZA_UX3402ZA 1.0 
               `+oooooo:                 Kernel: 6.8.7-zen1-2-zen 
               -+oooooo+:                Uptime: 2 days, 12 hours, 50 mins 
             `/:-:++oooo+:               Packages: 1233 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 2880x1800 
          `/+++ooooooooooooo/`           DE: Plasma 6.0.4 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         Theme: Breeze-Dark [GTK2], Breeze [GTK3] 
       -osssssso.      :ssssssso.        Icons: breeze-dark [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: konsole 
     /ossssssss/        +ssssooo/-       Terminal Font: JetBrainsMono Nerd Font 1 
   `/ossssso+/:-        -:/+osssso+-     CPU: 12th Gen Intel i7-1260P (16) @ 4.70 
  `+sso+:-`                 `.-/+oso:    GPU: Intel Alder Lake-P GT2 [Iris Xe Gra 
 `++:.                           `-/+/   Memory: 6602MiB / 15616MiB 
 .`                                 `/
```

**Comment by ChingCdesu** [comment]
贴一下node版本

**Comment by Eletary** [comment]
抱歉忘记看了

```
❯ node -v
v22.4.1
```

**Comment by Eletary** [comment]
？日志里第三行有这个

```
[main /resources/app/packages/main/index.ts:30:8 Object.<anonymous>] Node version: 18.16.1
```

我不太懂 /yun
