### ISSUE TITLE
无法下载 MaaCore： Failed to retrieve core update asset

### ISSUE THREAD

**Issue by D3adEr1c** [MaaAssistantArknights/MeoAsstElectronUI#220]
### 问题描述

# Environment
archlinux x86_64
linux: 6.9.3-zen1-1-zen
系统安装 node 22.2.0

但根据 log，使用的 node 版本为 18
```
2024-06-04 17:18:39.640	INFO	[main /resources/app/packages/main/index.ts:28:8 Object.<anonymous>] Electron version: 26.0.0
2024-06-04 17:18:39.749	INFO	[main /resources/app/packages/main/index.ts:29:8 Object.<anonymous>] Chromium version: 116.0.5845.82
2024-06-04 17:18:39.750	INFO	[main /resources/app/packages/main/index.ts:30:8 Object.<anonymous>] Node version: 18.16.1
```

# Version
dev 分支，按照 readme 编译

# Log
2024-06-04 17:23:35.887 点击安装核心
[Maa App-20240604.log](https://github.com/user-attachments/files/15545893/Maa.App-20240604.log)

**Comment by D3adEr1c** [comment]
补充：
小概率触发 gh.cirno.xyz 403 Forbidden
```
2024-06-04 17:48:23.534	ERROR	[main /resources/app/packages/main/componentManager/utils/release.ts:23:14 f1] [Component Installer | Maa Core] Error request on URL: https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaRelease/releases, attempts: 1/3,  Error: ERR_BAD_REQUEST | 403 Forbidden
AxiosError: Request failed with status code 403
    at settle (/home/d3ader1c/MaaX-linux64/resources/app/node_modules/axios/lib/core/settle.js:19:12)
    at BrotliDecompress.handleStreamEnd (/home/d3ader1c/MaaX-linux64/resources/app/node_modules/axios/lib/adapters/http.js:570:11)
    at BrotliDecompress.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-06-04 17:48:24.383	ERROR	[main /resources/app/packages/main/componentManager/utils/release.ts:23:14 f1] [Component Installer | Maa Core] Error request on URL: https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaRelease/releases, attempts: 2/3,  Error: ERR_BAD_REQUEST | 403 Forbidden
AxiosError: Request failed with status code 403
    at settle (/home/d3ader1c/MaaX-linux64/resources/app/node_modules/axios/lib/core/settle.js:19:12)
    at BrotliDecompress.handleStreamEnd (/home/d3ader1c/MaaX-linux64/resources/app/node_modules/axios/lib/adapters/http.js:570:11)
    at BrotliDecompress.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-06-04 17:48:25.007	ERROR	[main /resources/app/packages/main/componentManager/utils/release.ts:23:14 f1] [Component Installer | Maa Core] Error request on URL: https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaRelease/releases, attempts: 3/3,  Error: ERR_BAD_REQUEST | 403 Forbidden
AxiosError: Request failed with status code 403
    at settle (/home/d3ader1c/MaaX-linux64/resources/app/node_modules/axios/lib/core/settle.js:19:12)
    at BrotliDecompress.handleStreamEnd (/home/d3ader1c/MaaX-linux64/resources/app/node_modules/axios/lib/adapters/http.js:570:11)
    at BrotliDecompress.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-06-04 17:48:25.009	ERROR	[main /resources/app/packages/main/componentManager/utils/update.ts:101:14 Ss.checkUpdate] [Component Installer | Maa Core] Failed to retrieve core update asset
```

**Comment by D3adEr1c** [comment]
尝试打印 [update.ts](https://github.com/MaaAssistantArknights/MaaX/blob/dev/packages/main/componentManager/utils/update.ts) 中 L98 的item，得到 undefined

在 [MaaRelease](https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaRelease/releases) 中搜索不到满足正则表达式 `MAA-v(.+)-linux-x86_64\.tar\.gz` 的包

我在 https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaAssistantArknights/releases 中找到 `"name": "MAA-v5.3.1-linux-x86_64.tar.gz"`

是否可以更改检查 MaaCore 版本的 API？或者将 linux 构建添加到 MaaRelease ？
