### ISSUE TITLE
未知错误 arrch64

### ISSUE THREAD

**Issue by Xraytest** [MaaAssistantArknights/MeoAsstElectronUI#222]
### 问题描述

启动时报错
设备rpi4 debian12 xrdp环境

### 日志文件

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /home/xray4668/clonefile/maax/maa-x-linux-arm64/resources/app/node_modules/@tigerconnect/ffi-napi/build/Release/ffi_bindings.node: æ æ³æ	å¼å
±äº«å¯¹è±¡æä»¶: æ²¡æ	é£ä¸ªæä»¶æç
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at load (/home/xray4668/clonefile/maax/maa-x-linux-arm64/resources/app/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/home/xray4668/clonefile/maax/maa-x-linux-arm64/resources/app/node_modules/@tigerconnect/ffi-napi/lib/bindings.js:8:43)

**Comment by li-chx** [comment]
遇到了一样的错误
```
~/maax/maa-x-linux-arm64 ❯ ./maa-x                               base 00:38:41
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /home/lichx/maax/maa-x-linux-arm64/resources/app/node_modules/@tigerconnect/ffi-napi/build/Release/ffi_bindings.node: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at load (/home/lichx/maax/maa-x-linux-arm64/resources/app/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/home/lichx/maax/maa-x-linux-arm64/resources/app/node_modules/@tigerconnect/ffi-napi/lib/bindings.js:8:43)
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
```
奇怪的是 对应位置是有这个文件的，改成777也不行

**Comment by li-chx** [comment]
> 遇到了一样的错误
> 
> ```
> ~/maax/maa-x-linux-arm64 ❯ ./maa-x                               base 00:38:41
> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: /home/lichx/maax/maa-x-linux-arm64/resources/app/node_modules/@tigerconnect/ffi-napi/build/Release/ffi_bindings.node: cannot open shared object file: No such file or directory
>     at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
>     at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
>     at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
>     at Module.load (node:internal/modules/cjs/loader:1126:32)
>     at node:internal/modules/cjs/loader:967:12
>     at Function._load (node:electron/js2c/asar_bundle:2:13330)
>     at Module.require (node:internal/modules/cjs/loader:1150:19)
>     at require (node:internal/modules/cjs/helpers:110:18)
>     at load (/home/lichx/maax/maa-x-linux-arm64/resources/app/node_modules/node-gyp-build/node-gyp-build.js:22:10)
>     at Object.<anonymous> (/home/lichx/maax/maa-x-linux-arm64/resources/app/node_modules/@tigerconnect/ffi-napi/lib/bindings.js:8:43)
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> ```
> 
> 奇怪的是 对应位置是有这个文件的，改成777也不行

追评 系统是Armbian 24.8.4 noble orangePi5 RK3588s 的板子
